import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./_providers/AuthProvider";
import LoginModal from "./(auth)/_components/LoginModal";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="font-Pretendard"
      >
        <AuthProvider>
          {children}
          <LoginModal />
        </AuthProvider>
      </body>
    </html>
  );
}
